application: webhook-1000
version: 1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: github-webhook.app

libraries:
- name: webapp2
  version: "2.5.2"
